POST http://localhost:3000/jobs/create HTTP/1.1
Content-Type: "application/json"

{
  "title": "Data Analyst",
  "description": "We are seeking a skilled Data Analyst to join our team and help us analyze large datasets.",
  "location": "Austin, TX",
  "salary": 80000,
  "requirements": "Bachelor's degree in statistics or related field, experience with data analysis software such as Python or R"
}







# GET http://localhost:3000/jobs